name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        day: [1,2,3,4,5]

    name: Day ${{ matrix.day }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: 2021/day${{ matrix.day }}
      run: cargo build --verbose
    - name: Run tests
      working-directory: 2021/day${{ matrix.day }}
      run: cargo test --verbose
